import { z } from "zod";

export const formSchema = z.object({
  fullName: z.string().min(2),
  dob: z.string().min(4),
  gender: z.enum(["Male", "Female"]),
  placeOfBirth: z.string().min(2),
  nationality: z.string().min(2),
  religion: z.string().optional(),
  address: z.string().min(2),
  contact: z.string().min(10),

  primarySchool: z.string().min(2),
  currentSchool: z.string().min(2),
  location: z.string().min(2),
  livingArrangement: z.enum(["Hostel", "Day Scholar", "Combination", "Other"]),
  otherLiving: z.string().optional(),
  level: z.string().min(2),
  attendsSeminary: z.enum(["Yes", "No"]),
  seminaryName: z.string().optional(),
  seminaryTeacher: z.string().optional(),
  mosque: z.string().optional(),

  fatherName: z.string().min(2),
  fatherResidence: z.string().min(2),
  fatherOccupation: z.string().min(2),
  fatherContact: z.string().min(10),
  fatherEmail: z.string().email().optional(),
  motherName: z.string().min(2),
  motherResidence: z.string().min(2),
  motherOccupation: z.string().min(2),
  motherContact: z.string().min(10),
  motherEmail: z.string().email().optional(),
  guardianName: z.string().optional(),
  guardianRelation: z.string().optional(),
  guardianResidence: z.string().optional(),
  guardianOccupation: z.string().optional(),
  guardianContact: z.string().optional(),
  guardianEmail: z.string().optional(),

  feeStructureAttached: z.enum(["Yes", "No"]),
  annualFees: z.string().min(2),
  accountName: z.string().min(2),
  accountNumber: z.string().min(2),
  paybillNumber: z.string().min(2),
  receivedAid: z.enum(["Yes", "No"]),
  aidDetails: z.string().optional(),
  obligations: z.string().min(2),

  background: z.string().min(10),
  reason: z.string().min(10),
  aspirations: z.string().min(5),
  notes: z.string().optional(),

  birthCert: z.boolean(),
  kcpe: z.boolean(),
  primaryLeaving: z.boolean(),
  kcse: z.boolean(),
  secondaryLeaving: z.boolean(),
  reportForms: z.boolean(),
  idCopies: z.boolean(),
  feeStructure: z.boolean(),
  photo: z.boolean(),

  documents: z.any().optional(),
});
